version: "3.8"
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=backend

    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env


  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: my-docker-api
    volumes:
      - .:/app
    ports: 
      - 3000:3000
    depends_on:
      - db 
    env_file:
      - .env
    environment:
      - DB_NAME=backend
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DIALECT=mysql
      - NODE_ENV=development
      
    #command: npm start
    command: sh -c "npm install && npx sequelize-cli db:migrate && npx sequelize-cli db:seed:all && npm start"


volumes: 
  mysql-volume:
